included:
  - EMS

opt_in_rules:
  - attributes
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - empty_xctest_method
  - first_where
  - for_where
  - force_cast
  - force_try
  - identical_operands
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - xct_specific_matcher
  - xctfail_message

custom_rules:
  ks_conditional_returns_on_newline:
    included: ".*\\.swift"
    name: "Custom Conditional Returns On New Line"
    regex: "(if)[^\n]*return"
    message: "Hey look at the the conditional returns on newline for if else"
    severity: warning

disabled_rules:
  - cyclomatic_complexity
  - large_tuple
  - private_over_fileprivate
  - type_name
  - inclusive_language

identifier_name:
  min_length: 2
  max_length: 55

line_length: 150

function_body_length: 100

file_length:
  warning: 400
  error: 500

function_parameter_count:
  warning: 8
  error: 10
